# permissions for end users to view adsslissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adsslissuer-viewer-role
rules:
- apiGroups:
  - certmanager.tomdoherty.io
  resources:
  - adsslissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certmanager.tomdoherty.io
  resources:
  - adsslissuers/status
  verbs:
  - get
