# permissions for end users to edit adsslissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adsslissuer-editor-role
rules:
- apiGroups:
  - certmanager.tomdoherty.io
  resources:
  - adsslissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmanager.tomdoherty.io
  resources:
  - adsslissuers/status
  verbs:
  - get
